language: cpp

compiler: gcc

before_script:
  - sudo apt-get update
  - sudo apt-get install libgtest-dev
  - mkdir src/build
  - cd src/build
  - cmake ..

script: make

notifications:
  email:
    - marcin.kolny@gmail.com
    - pawel.matyszok@gmail.com
  on_success: change
  on_failure: always
